baseURL = 'https://thisisjab.github.io/'
locale = 'en-us'
title = '<thisisjab/>'
theme = 'nostyleplease'

taxonomies = { tag = "tags" }

cascade.params = { toc = false, tocBorder = false }

[markup]
  [markup.highlight]
    codeFences         = true
    anchorLineNos = true
    guessSyntax        = false
    lineNos            = true 
    lineNumbersInTable = false 
    noClasses          = true 
    hl_inline = false 
    # style = 'catppuccin-frappe'
    # style              = 'modus-vivendi'
    style = 'xcode-dark'

  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 3
    ordered    = false

[params]
  style = "css/main.scss"

  [params.theme_config]
    appearance        = "auto"
    back_home_text    = "<<<"
    date_format       = "2006-01-02"
    isListGroupByDate = false
    isShowFooter      = false 
